export enum CommonErrorCode {
	UNKNOWN_ERROR = "UNKNOWN_ERROR",
	NOT_HANDLED_ERROR = "NOT_HANDLED_ERROR",
	INTERNAL_ERROR = "INTERNAL_ERROR",
	INVALID_QUERY_OBJECT = "INVALID_QUERY_OBJECT",
	MISSING_FIELD = "MISSING_FIELD",
	INVALID_VALUE = "INVALID_VALUE",
}
